name: Check Rust

on: [push, pull_request]

jobs:
  ci:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up cargo cache
        uses: Swatinem/rust-cache@v2

      - name: install dependencies (ubuntu only)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
        

      - name: Cargo Build
        run: cargo build
        working-directory: src-tauri

    # Uncomment the following lines if we have tests 
    #   - name: Cargo Test
    #     run: cargo test
    #     working-directory: src-tauri

      - name: Cargo Fmt
        run: cargo fmt --all -- --check
        working-directory: src-tauri

      - name: Cargo Clippy
        run: cargo clippy -- -D warnings
        working-directory: src-tauri
